services:
  rsync-target:
    build: .
    container_name: cfs-transfer-target
    restart: unless-stopped
    privileged: true
    environment:
      - LOCAL_PATH=${LOCAL_PATH:-/mnt}
      - NFS_SERVER=${NFS_SERVER}
      - NFS_PATH=${NFS_PATH:-/cfs}
      - NFS_O_PARAMETER=${NFS_O_PARAMETER:-vers=3,noresvport,nolock}
      - RSYNC_PASSWORD=${RSYNC_PASSWORD:-changeme}
      - RSYNC_USER=${RSYNC_USER:-root}
      - RSYNC_PORT=${RSYNC_PORT:-873}
      - MAX_CONNECTIONS=${MAX_CONNECTIONS:-200}
      - TZ=Asia/Shanghai
    
    ports:
      - "${RSYNC_PORT}:873"
    
    volumes:
      # - ${DATA_PATH}:/data
      - ./logs:/var/log
    
    networks:
      - cfs-network
    
    healthcheck:
      test: ["CMD", "pgrep", "rsync"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  cfs-network:
    driver: bridge
